services:
  freesurfer:
    image: idossha/ti-toolbox_freesurfer:v7.4.1
    platform: linux/amd64
    container_name: freesurfer_container
    volumes:
      - ti-toolbox_freesurfer_data:/usr/local/freesurfer/
    networks:
      - ti_network
    restart: unless-stopped

  simnibs:
    image: idossha/simnibs:v2.1.3
    platform: linux/amd64
    container_name: simnibs_container
    volumes:
      - ti-toolbox_freesurfer_data:/usr/local/freesurfer/
      - ${LOCAL_PROJECT_DIR}:/mnt/${PROJECT_DIR_NAME}
      # X11 socket mount for Linux/macOS
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Additional mount for macOS XQuartz compatibility
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    environment:
      # User environment
      USER: root
      # Display configuration
      DISPLAY: ${DISPLAY}
      # OpenGL configuration for software rendering (better compatibility)
      LIBGL_ALWAYS_SOFTWARE: "1"
      QT_X11_NO_MITSHM: "1"
      # FreeSurfer environment
      FREESURFER_HOME: /usr/local/freesurfer
      SUBJECTS_DIR: /usr/local/freesurfer/subjects
      FS_LICENSE: /usr/local/freesurfer/license.txt
      # Project paths
      LOCAL_PROJECT_DIR: ${LOCAL_PROJECT_DIR}
      PROJECT_DIR_NAME: ${PROJECT_DIR_NAME}
      # Performance settings
      KMP_AFFINITY: "disabled"
    networks:
      - ti_network
    depends_on:
      - freesurfer
    tty: true
    stdin_open: true
    working_dir: /ti-toolbox
    command: ["/bin/bash"]
    restart: unless-stopped

networks:
  ti_network:
    driver: bridge

volumes:
  ti-toolbox_freesurfer_data:
    external: true
    name: ti-toolbox_freesurfer_data

